[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyplaner"
version = "0.1.0"
description = "A chicken-planner PDF generation library"
authors = [
    { name = "Vlad Vovchenko", email = "vlad.vovchenko93@gmail.com" }
]
readme = "README.rst"
requires-python = ">=3.12"

dependencies = [
    "jinja2>=3.1",
    "playwright>=1.58"
]

[project.optional-dependencies]
pikepdf = ["pikepdf>=10.3"]
